ComfyBag=ComfyBag or {}
local A=ComfyBag
A.itemButtons=A.itemButtons or {}
local function NumSlots(bag) if C_Container and type(C_Container.GetContainerNumSlots)=="function" then local ok,v=pcall(C_Container.GetContainerNumSlots,bag); if ok then return tonumber(v) or 0 end end if type(GetContainerNumSlots)=="function" then local ok,v=pcall(GetContainerNumSlots,bag); if ok then return tonumber(v) or 0 end end return 0 end
local function Info(bag,slot) if C_Container and type(C_Container.GetContainerItemInfo)=="function" then local ok,i=pcall(C_Container.GetContainerItemInfo,bag,slot); if ok and type(i)=="table" then return i.iconFileID,i.stackCount,i.quality,i.hyperlink end end if type(GetContainerItemInfo)=="function" then local ok,t,c,_,q,_,_,l=pcall(GetContainerItemInfo,bag,slot); if ok then return t,c,q,l end end end
local function Link(bag,slot) if C_Container and type(C_Container.GetContainerItemLink)=="function" then local ok,v=pcall(C_Container.GetContainerItemLink,bag,slot); if ok then return v end end if type(GetContainerItemLink)=="function" then local ok,v=pcall(GetContainerItemLink,bag,slot); if ok then return v end end end
local function UseItem(bag,slot) local fn=C_Container and C_Container.UseContainerItem or UseContainerItem; if type(fn)=="function" then return pcall(fn,bag,slot) end return false end
local function MoneyText(copper) copper=tonumber(copper) or 0; if type(GetMoneyString)=="function" then local ok,t=pcall(GetMoneyString,copper,true); if ok and t then return t end end; local g=math.floor(copper/10000); local s=math.floor((copper%10000)/100); local c=copper%100; return string.format("%dg %ds %dc",g,s,c) end
function A:SellJunk() if not self.db or not self.db.enabled or not self.db.bag.autoSellJunk then return end; if InCombatLockdown and InCombatLockdown() then return end; local value=0; local sold=0; for bag=0,4 do for slot=1,NumSlots(bag) do local _,count,q,link=Info(bag,slot); link=link or Link(bag,slot); if tonumber(q)==0 and link and type(GetItemInfo)=="function" then local ok,_,_,_,_,_,_,_,_,_,price=pcall(GetItemInfo,link); price=ok and tonumber(price) or 0; if price>0 and UseItem(bag,slot) then value=value+price*math.max(1,tonumber(count) or 1); sold=sold+1 end end end end; if sold>0 then self:Print(self:T("SOLD_JUNK")..": "..MoneyText(value)) end end
function A:CreateBagWindow() if self.bagFrame then return end local f=CreateFrame("Frame","ComfyBagWindow",UIParent,"BasicFrameTemplateWithInset"); f:SetSize(520,430); f:SetFrameStrata("HIGH"); f:SetClampedToScreen(true); f:SetMovable(true); f:EnableMouse(true); f:RegisterForDrag("LeftButton"); f.TitleText:SetText("ComfyBag"); f:SetScript("OnDragStart",function(self) self:StartMoving() end); f:SetScript("OnDragStop",function(self) self:StopMovingOrSizing(); local p,_,rp,x,y=self:GetPoint(1); A.db.bagWindow={point=p,relativePoint=rp or p,x=x or 0,y=y or 0} end); local p=self.db.bagWindow or {}; f:SetPoint(p.point or "CENTER",UIParent,p.relativePoint or p.point or "CENTER",p.x or 0,p.y or 0); f:Hide(); table.insert(UISpecialFrames,f:GetName()); local s=CreateFrame("EditBox",nil,f,"InputBoxTemplate"); s:SetSize(220,28); s:SetPoint("TOPLEFT",20,-32); s:SetAutoFocus(false); s:SetScript("OnTextChanged",function(self) A.searchText=(self:GetText() or ""):lower(); A:RefreshFeature() end); s:SetScript("OnEscapePressed",function(self) self:ClearFocus() end); f.search=s; self.bagFrame=f end
function A:GetButton(i) local b=self.itemButtons[i]; if b then return b end b=CreateFrame("Button",nil,self.bagFrame,"BackdropTemplate"); b:SetSize(38,38); b:SetBackdrop({edgeFile="Interface\\Buttons\\WHITE8X8",edgeSize=1}); b.icon=b:CreateTexture(nil,"ARTWORK"); b.icon:SetPoint("TOPLEFT",2,-2); b.icon:SetPoint("BOTTOMRIGHT",-2,2); b.icon:SetTexCoord(0.07,0.93,0.07,0.93); b.count=b:CreateFontString(nil,"OVERLAY","NumberFontNormal"); b.count:SetPoint("BOTTOMRIGHT",-3,3); b:SetScript("OnEnter",function(self) if self.link then GameTooltip:SetOwner(self,"ANCHOR_RIGHT"); GameTooltip:SetHyperlink(self.link); GameTooltip:Show() end end); b:SetScript("OnLeave",function() GameTooltip:Hide() end); b:SetScript("OnClick",function(self) if InCombatLockdown and InCombatLockdown() then A:Print(A:T("COMBAT_LOCK")); return end local fn=C_Container and C_Container.UseContainerItem or UseContainerItem; if type(fn)=="function" then pcall(fn,self.bag,self.slot) end end); self.itemButtons[i]=b; return b end
function A:RefreshFeature() self:CreateBagWindow(); if not self.db.enabled then self.bagFrame:Hide(); return end; self.bagFrame.search:SetShown(self.db.bag.showSearch~=false); if not self.bagFrame:IsShown() then return end; local cols=math.max(6,math.min(16,tonumber(self.db.bag.columns) or 10)); local needle=tostring(self.searchText or ""):lower(); local idx=0; for bag=0,4 do for slot=1,NumSlots(bag) do local tex,count,q,link=Info(bag,slot); link=link or Link(bag,slot); local show=true; if needle~="" then local name=link and link:match("%[(.-)%]") or ""; show=tostring(name):lower():find(needle,1,true)~=nil end; if show then idx=idx+1; local b=self:GetButton(idx); b.bag=bag; b.slot=slot; b.link=link; b.icon:SetTexture(tex or "Interface\\Icons\\INV_Misc_QuestionMark"); b.count:SetText((tonumber(count) or 0)>1 and tostring(count) or ""); local cs={[0]={.3,.3,.3},[1]={1,1,1},[2]={.12,1,0},[3]={0,.44,.87},[4]={.64,.21,.93},[5]={1,.5,0}}; local c=cs[tonumber(q) or 0] or cs[0]; b:SetBackdropBorderColor(c[1],c[2],c[3],.9); b:ClearAllPoints(); local col=(idx-1)%cols; local row=math.floor((idx-1)/cols); b:SetPoint("TOPLEFT",20+col*42,-70-row*42); b:Show() end end end; for i=idx+1,#self.itemButtons do self.itemButtons[i]:Hide() end; local rows=math.max(1,math.ceil(idx/cols)); self.bagFrame:SetSize(math.max(360,40+cols*42),math.max(200,105+rows*42)) end
function A:ToggleBag() self:CreateBagWindow(); if self.bagFrame:IsShown() then self.bagFrame:Hide() else self.bagFrame:Show(); self:RefreshFeature() end end
function A:HandleSlash(msg) if msg=="options" or msg=="config" then return false end self:ToggleBag(); return true end
function A:InitializeFeature() self:CreateBagWindow(); local e=CreateFrame("Frame"); for _,ev in ipairs({"BAG_UPDATE_DELAYED","BAG_UPDATE_COOLDOWN","PLAYER_ENTERING_WORLD","MERCHANT_SHOW"}) do pcall(e.RegisterEvent,e,ev) end; e:SetScript("OnEvent",function(_,ev) if ev=="MERCHANT_SHOW" then A:SellJunk() end; A:RefreshFeature() end) end
function A:BuildGeneralOptions(page,ui) ui.CreateSlider(page,A:T("COLUMNS"),6,16,1,35,-120,function() return A.db.bag.columns end,function(v) A.db.bag.columns=math.floor(v+0.5) end,function(v) return tostring(math.floor(v+0.5)) end); ui.CreateCheck(page,A:T("SHOW_SEARCH"),20,-190,function() return A.db.bag.showSearch end,function(v) A.db.bag.showSearch=v end); ui.CreateCheck(page,A:T("AUTO_SELL_JUNK"),20,-225,function() return A.db.bag.autoSellJunk end,function(v) A.db.bag.autoSellJunk=v end); ui.CreateButton(page,A:T("OPEN_BAG"),20,-280,150,function() A:ToggleBag() end); local n=page:CreateFontString(nil,"ARTWORK","GameFontHighlightSmall"); n:SetPoint("TOPLEFT",20,-350); n:SetWidth(680); n:SetJustifyH("LEFT"); n:SetText(A:T("FOREVER_NOTE")) end
